# Generated by Django 5.2.7 on 2025-10-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(max_length=100, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
