# Generated by Django 5.2.7 on 2025-10-25 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
