# Generated by Django 5.2.7 on 2025-10-26 15:16

import attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userface',
            name='image_filename',
        ),
        migrations.AddField(
            model_name='userface',
            name='face_image',
            field=models.ImageField(default='', upload_to=attendance.models.face_upload_path),
            preserve_default=False,
        ),
    ]
