# Generated by Django 5.2.7 on 2025-10-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='time',
            new_name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='student_id',
        ),
        migrations.AddField(
            model_name='attendance',
            name='user_face',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.userface'),
            preserve_default=False,
        ),
    ]
